# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true


# General Jekyll Config
title: 'Victoria N.' 
tagline: ' - - Portfolio'
description:         ''
url:                 http://victorianavarro@github.io
baseurl:             '/'
paginate:            5



# This will require each of these plugins automatically.
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - another-jekyll-plugin


