# General Jekyll Config
highlighter:rogue
name:Victoria N
description: Victoria's Portfolio
url: https://vnf89.github.io/
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]


# This will require each of these plugins automatically.
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - another-jekyll-plugin

# Activate a theme
theme: minima
remote_theme: benbalter/retlab

