# This will require each of these plugins automatically.
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - another-jekyll-plugin

# Activate a theme
theme: minima
remote_theme: benbalter/retlab

